server:
  port: 8080
  servlet:
    context-path: /dang

spring:
  main:
    banner-mode: off
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/movie_ticket}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:2503}

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

cloudinary:
  cloud_name: dkd0crnyd
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}


seatsPerRow: 20

jwt:
  signerKey: "h7FxX3w7j5lJ5X6P6IEDEG052ECmUocmpnNK3uNgOpL3SXlgwz/OnsgAWnGHR+K4"
  valid-duration: 3600 #seconds
  refreshable-duration: 360000 #seconds

#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.format_sql=true
#  spring.jpa.properties.hibernate.use_sql_comments=true
#  logging.level.org.hibernate=DEBUG

# Swagger
openapi:
  service:
    api-docs: api-service
    title: API document
    version: 1.0.0
    server: http://localhost:${server.port}/dang

logging:
  level:
    org:
      springframework:
        security: DEBUG